import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useEffect, useMemo, useState } from 'react';
import { createHttpClient } from '@/utils/http-client';
import { ExternalWindow } from '@/utils/external-window';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const httpClient = useMemo(() => createHttpClient({
    baseURL: 'https://localhost:7061',
    tokens: {
      generate: async (client, provider, credentials) => {
        if (provider == null) {
          return client.post('/accounts/sessions/generate', credentials);
        }
        else {

          try {
            const externalURL = new URL(`${client.defaults.baseURL}/accounts/${provider}/sessions/connect`);
            externalURL.searchParams.set('origin', window.origin);

            await new ExternalWindow(externalURL.toString(), { center: true }).open();
          }
          catch (error) { }

          return await client.post(`/accounts/${provider}/sessions/generate`);
        }
      },
      refresh: (client, token) => client.post('/accounts/sessions/refresh', { refreshToken: token }),
      revoke: (client, token) => client.post('/accounts/sessions/revoke', { refreshToken: token }),
    }
  }), []);


  const [user, setUser] = useState(httpClient.user.value);

  useEffect(() => {
    httpClient.user.subscribe((value) => {
      setUser(value)
    });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
            onClick={(e) => {
              e.preventDefault();
              httpClient.signIn({ username: 'princeowusu.272@gmail.com', password: 'Owusu#15799' });
            }}
          >
            <h2 className={inter.className}>
              SignIn with Internal <span>-&gt;</span>
            </h2>
          </a>
          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
            onClick={(e) => {
              e.preventDefault();
              httpClient.signInWith('google');
            }}
          >
            <h2 className={inter.className}>
              SignIn with External <span>-&gt;</span>
            </h2>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
            onClick={(e) => {
              e.preventDefault();
              httpClient.get('/protected');
            }}
          >
            <h2 className={inter.className}>
              Access Resource <span>-&gt;</span>
            </h2>
          </a>
          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
            onClick={async (e) => {
              e.preventDefault();

              console.log('Closed')
            }}
          >
            <h2 className={inter.className}>
              Open External Window <span>-&gt;</span>
            </h2>
          </a>
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>

          <div className={styles.card}><div className={inter.className}>User: {JSON.stringify(user)}</div></div>
        </div>

      </main>
    </>
  )
}
